# Generated by Django 4.2.14 on 2024-07-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_options_alter_menuelement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='main_menu_element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='menu.menuelement', verbose_name='основной элемент меню'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='menuelement',
            name='text',
            field=models.CharField(max_length=100, unique=True, verbose_name='текст'),
        ),
    ]
