# Generated by Django 4.2.14 on 2024-07-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_main_menu_element_alter_menu_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuelement',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
