# Generated by Django 4.2.14 on 2024-07-24 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menuelement_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuelement',
            name='parent_menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='menu.menu', verbose_name='меню'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='main_menu_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuelement', verbose_name='основной элемент меню'),
        ),
    ]
