# Generated by Django 4.2.14 on 2024-07-25 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuelement_parent_menu_alter_menu_main_menu_element'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='main_menu_element',
        ),
    ]
